### ISSUE TITLE
OSError: [Errno 2] No such file or directory ...

### ISSUE THREAD

**Issue by aiamuzz** [jenom/pdfbook2#1]
Hi,

I tried your package ... encountered the following errors ... `./pdfbook2 --paper=a4paper --inner-margin=200 LandAcquisitionSummary.pdf`

**Errors :** 

```
    pdfbook2 v1.3 (https://github.com/jenom/pdfbook2)
    (c) 2015 Johannes Neumann (http://www.neumannjo.de)
    licensed under GPLv3 (http://www.gnu.org/licenses/gpl-3.0)
    based on pdfbook by David Firth with help from Marco Pessotto


Processing LandAcquisitionSummary.pdf
Getting bounds...
Traceback (most recent call last):
  File "./pdfbook2", line 234, in <module>
    booklify( arg, opts )
  File "./pdfbook2", line 49, in booklify
    stderr = subprocess.PIPE )
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

```

**Comment by jenom** [comment]
It looks like you don't have pdfcrop installed. Did you install pdfbook2 via the texlive sources? They should come with all requirements.

**Comment by j-balint** [comment]
I have the same problem, although **pdfcrop** is installed:

balint@Aspire-V3 ~/Asztal $ pdfbook2 bosch.pdf
    pdfbook2 v1.2
    (c) 2015 Johannes Neumann (http://www.neumannjo.de)
    licensed under GPLv3 (http://www.gnu.org/licenses/gpl-3.0)
    based on pdfbook by David Firth with help from Marco Pessotto
Processing bosch.pdf
Getting bounds... done
cropping... done
create booklet...
Traceback (most recent call last):
  File "/usr/bin/pdfbook2", line 237, in <module>
    booklify( arg, opts )
  File "/usr/bin/pdfbook2", line 140, in booklify
    os.rename( tmpFile[:-4] + "-book.pdf", name[:-4] + "-book.pdf" )
OSError: [Errno 2] No such file or directory

best regards.

**Comment by veromary** [comment]
me too
```
Processing main.pdf
Getting bounds... done
cropping... done
create booklet... Traceback (most recent call last):
  File "/home/veronica/bin/pdfbook2", line 318, in <module>
    booklify(arg, opts)
  File "/home/veronica/bin/pdfbook2", line 161, in booklify
    os.rename(tmpFile[:-4] + "-book.pdf", name[:-4] + "-book.pdf")
FileNotFoundError: [Errno 2] No such file or directory: '.crop-tmp-book.pdf' -> 'main-book.pdf'
```

Strangely enough, it has created a file .crop-tmp-book.pdf which is a large file much like the original file, except cropped differently.

I'm using Linux Mint, with TinyTeX as the ubuntu sources are stuck at Texlive 2015.

**Comment by jenom** [comment]
Thanks a lot for the input. As soon as I have time I will try to reproduce this in a VM with Mint as I cannot reproduce this in Ubuntu with TexLive 2019. It sounds like a problem with path handling. 

The .crop-tmp-book.pdf file is a temporary file that is cropped but not yet arranged.

**Comment by veromary** [comment]
It turned out I hadn't installed pdfpages. Or pdflscape. It was easier to debug by running pdfjam.

**Comment by Foorack** [comment]
I had to install `sudo apt-get install texlive-latex-recommended` on Ubuntu for it to work. Otherwise, I got the same error as in https://github.com/jenom/pdfbook2/issues/1#issuecomment-588528774
